enum ActionTypes {
  // ASYNC INNER (SYNC ACTIONS)
  INNER_SET_STATE_AXES = 'INNER_SET_STATE_AXES',
  INNER_RESET_STATE_AXES = 'INNER_RESET_STATE_AXES',
  INNER_INITIALIZE_STATE = 'INNER_INITIALIZE_STATE',
  INNER_SET_CALCULATED = 'INNER_SET_CALCULATED',
  INNER_SET_CONFIG = 'INNER_SET_CONFIG',

  INNER_SET_NEW_CALC = 'INNER_SET_NEW_CALC',
  INNER_SET_NEW_STORE = 'INNER_SET_NEW_STORE',
  // ASYNC
  SET_AXES = 'SET_AXES',
  PUSH_TO_ARDUINO = 'PUSH_TO_ARDUINO',
  RESET_AXES = 'RESET_AXES',
  APPLY_CONFIG = 'APPLY_CONFIG',
  // SYNC
  SET_LIVE_INPUT = 'SET_LIVE_INPUT',
}

export default ActionTypes;
