enum ActionTypes {
  // ASYNC INNER (SYNC ACTIONS)
  INNER_SET_STATE_AXES = 'INNER_SET_STATE_AXES',
  INNER_SET_NEW_CALC = 'INNER_SET_NEW_CALC',
  INNER_SET_NEW_STORE = 'INNER_SET_NEW_STORE',
  // ASYNC
  SET_AXES = 'SET_AXES',
  // SYNC
  SET_LIVE_INPUT = 'SET_LIVE_INPUT',
}

export default ActionTypes;
